### ISSUE TITLE
Query failed: Code 401

### ISSUE THREAD

**Issue by fieu** [terror/usernames#2]
I can't seem to use the program. The GraphQL query seems to return a 401 for some reason.

```
➜  usernames git:(master) python3 main.py -i wordlists/animals/random.txt -o avail.txt
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    main()
  File "main.py", line 27, in main
    res = build_query(user.rstrip())["data"]
  File "main.py", line 102, in build_query
    return run_query(query, variables)
  File "main.py", line 70, in run_query
    raise Exception(
Exception: Query failed to run by returning code of 401.
    query userInfo($login: String!) {
            user(login: $login) {
              name
              login
              createdAt
              starredRepositories {
                totalCount
              }
              repositories {
                totalCount
              }
              following {
                totalCount
              }
              contributionsCollection {
                totalCommitContributions
                restrictedContributionsCount
                hasAnyContributions
              }
            }
        }
```

I have a `.env` file with a token with every privilege enabled.

**Comment by terror** [comment]
Do you have brackets around your token? If so, remove them and you should be fine

**Comment by fieu** [comment]
I tried:
```env
TOKEN=token_here
```
```env
TOKEN="token_here"
```
```env
TOKEN='token_here'
```
None have worked. Same error.

**Comment by terror** [comment]
Your .env should look like:

TOKEN="token token_here" where token_here is your token.

Example:

```
TOKEN="token 123456"
```

**Comment by m-graf** [comment]
It's important to note that if your token is `FOOBARBAZ` the correct format is:

```
TOKEN="token FOOBARBAZ"
```

There should be a preceding `token `.

**Comment by terror** [comment]
I updated the README to clarify this, @fieu let me know if the issue still persists.

**Comment by fieu** [comment]
Oh, well that would've been nice to know from the beginning. All good now.
