### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by JarnoXYZ** [terror/usernames#5]
Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 56, in main
    res = build_query(user.rstrip())["data"]
  File "main.py", line 103, in build_query
    return run_query(query, variables)
  File "main.py", line 71, in run_query
    raise requests.HTTPError(
requests.exceptions.HTTPError: Query failed to run by returning code of 401. 
    query userInfo($login: String!) {
            user(login: $login) {
              name
              login
              createdAt
              starredRepositories {
                totalCount
              }
              repositories {
                totalCount
              }
              following {
                totalCount
              }
              contributionsCollection {
                totalCommitContributions
                restrictedContributionsCount
                hasAnyContributions
              }
            }
        }

**Comment by terror** [comment]
See issue #2, let me know if that doesn't solve your issue.
